export enum Endpoints {
  CHAMPION_SELECT_ALL_CHAMPS = '/lol-champ-select/v1/all-grid-champions',
  CHAMPION_SELECT_CURRENT_CHAMPION = '/lol-champ-select-legacy/v1/current-champion',
  CHAT_ME = '/lol-chat/v1/me',
  TEAM_BUILDER_CURRENT_CHAMPION = '/lol-lobby-team-builder/champ-select/v1/current-champion',
  END_OF_GAME_STATS = '/lol-end-of-game/v1/eog-stats-block',
  INVITATIONS = '/lol-lobby/v2/lobby/invitations',
  FRIEND_GROUPS = '/lol-chat/v1/friend-groups',
  FRIENDS = '/lol-chat/v1/friends',
  FRIEND_REQUESTS = '/lol-chat/v1/friend-requests',
  GAMEFLOW_PHASE = '/lol-gameflow/v1/gameflow-phase',
  GAME_VERSION = '/lol-patch/v1/game-version',
  LOOT_MAP = '/lol-loot/v1/player-loot-map',
  LOOT_RECIPES = '/lol-loot/v1/recipes',
  READY_CHECK = '/lol-matchmaking/v1/ready-check',
  READY_CHECK_ACCEPT = '/lol-matchmaking/v1/ready-check/accept',
  RECENTLY_PLAYED_SUMMONERS = '/lol-match-history/v1/recently-played-summoners',
  SUMMONER_PROFILE = '/lol-summoner/v1/current-summoner/summoner-profile',
  WALLET = '/lol-store/v1/wallet'
}
