export enum LootRedeemableStatus {
  UNKNOWN = 'UNKNOWN',
  REDEEMABLE = 'REDEEMABLE',
  REDEEMABLE_RENTAL = 'REDEEMABLE_RENTAL',
  NOT_REDEEMABLE = 'NOT_REDEEMABLE',
  NOT_REDEEMABLE_RENTAL = 'NOT_REDEEMABLE_RENTAL',
  ALREADY_OWNED = 'ALREADY_OWNED',
  ALREADY_RENTED = 'ALREADY_RENTED',
  CHAMPION_NOT_OWNED = 'CHAMPION_NOT_OWNED',
  SKIN_NOT_OWNED = 'SKIN_NOT_OWNED'
}
